# Generated by Django 2.0.10 on 2019-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.AddField(
            model_name='criterion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
