# Generated by Django 2.0.10 on 2019-04-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190404_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
